### ISSUE TITLE
How does this plugin compare with its counterparts ?

### ISSUE THREAD

**Issue by ngirard** [moolmanruan/obsidian-sequence-hotkeys#23]
There are currently 4 plugins that apparently provide the same functionality.
Unfortunately, there is currently no information that would help to make an informed choice among them.
Could you please explain how your plugin differs from its counterparts ?

Here are the information I gathered about the aforementioned plugins, yours included:

**Chorded hotkeys**
DL:: 261
Updated:: 3 months ago
Issues:: 2
Commits:: 9
Version:: 1.0.0
obsidian://show-plugin?id=obsidian-chorded-hotkeys
https://github.com/ConnorMeyers/obsidian-chorded-hotkeys

**Sequence hotkeys**
DL:: 954
Updated:: 3 months ago
Issues:: 9
Commits:: 60
Version:: 0.5.1
obsidian://show-plugin?id=obsidian-sequence-hotkeys
https://github.com/moolmanruan/obsidian-sequence-hotkeys

**Hotkeys chords**
DL:: 446
Updated:: a year ago
Issues:: 2
Commits:: 47
Version:: 0.1.0
obsidian://show-plugin?id=obsidian-hotkeys-chords
https://github.com/trenta3/obsidian-hotkeys-chords

**Key sequence shortcut**
DL:: 840
Updated:: a year ago
Issues:: 6
Commits:: 18
Version:: 2.0.2
obsidian://show-plugin?id=obsidian-key-sequence-shortcut
https://github.com/anselmwang/obsidian-key-sequence-shortcut

Thanks very much in advance !
Cheers

**Comment by lukemt** [comment]
I think I compared it to at least one other plugin a while back and this was my favorite, but I do not know why anymore. However I I've been using it for over a year now and I am very pleased with how reliable it works! Anyways if you find any more information please write it here, because I do want to know too :)

**Comment by ghost** [comment]
Hi @ngirard, I looked at some of those others before I decided to create this plugin. They didn't give me the functionality I required, but can't remember the exact reasons. I'll have a look again if I get some time and post a summary.

**Comment by moolmanruan** [comment]
So I had a look at the other plugins mentioned. From those the closest one to this one is [trenta3's Hotkeys chords](https://github.com/trenta3/obsidian-hotkeys-chords); I tried using it for a while but I think the way you create hotkeys bothered me and I wanted something more in line with the built-in hotkeys.

I think the other two plugins mentioned are slightly different, since they go for chorded letter sequences, for example pressing two or more letters together (think piano chords).
